hlxsites/realmadrid

styles/styles.css
Fix #34
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/area-vip/partido-vip/silver-club-127
- After: https://bug-34-fix-h2--realmadrid--hlxsites.hlx.page/area-vip/partido-vip/silver-club-127
=> 34 - fix h2 in info-vip section

blocks/hero/hero.css, blocks/hero/hero.js, blocks/vip-areas/vip-areas.js, scripts/scripts.js
Taking a dig at adding video support in the hero block. Tried auto blocking the hero with video when video block is added at the top of the page.
Fix #18
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.live/drafts/vdua/area-vip
- After: https://hero-video--realmadrid--hlxsites.hlx.live/drafts/vdua/area-vip
=> feat: video in hero block

blocks/columns/columns.css, styles/styles.css
Fix #33
- Before: https://main--realmadrid--hlxsites.hlx.page//area-vip/partido-vip/silver-club-127
- After: https://33-vip-location-columns--realmadrid--hlxsites.hlx.page/area-vip/partido-vip/silver-club-127
=> 33 - vip area location columns

.gitignore, README.md, blocks/vip-sections/vip-sections.css, blocks/vip-sections/vip-sections.js, styles/styles.css
Fix #14 
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/drafts/grumaz/partido-vip
- After: https://14-cards-block--realmadrid--hlxsites.hlx.page/drafts/grumaz/partido-vip
=> Cards block for VIP Area

blocks/area-features/area-features.css, blocks/columns/columns.css, blocks/contact-card/contact-card.css, styles/styles.css
Fix #54
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/area-vip/partido-vip/silver-club-227
- After: https://54-overlap-issue--realmadrid--hlxsites.hlx.page/area-vip/partido-vip/silver-club-227
=> bug: fixing overlap of columns and area-features

helix-query.yaml
=> 5 - Custom index for vip area

blocks/vip-areas/vip-areas.js, scripts/scripts.js
Fix #56
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/area-vip
- After: https://fix-filter-areas-vip-from-index--realmadrid--hlxsites.hlx.page/area-vip, https://fix-filter-areas-vip-from-index--realmadrid--hlxsites.hlx.page/en/vip-area
=> fix: filter areas vip from index list

blocks/area-features/area-features.css, blocks/matches/matches.css, blocks/matches/matches.js
Fix #12 
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/drafts/vdua/partido-vip
- After: https://12-matches-block--realmadrid--hlxsites.hlx.page/drafts/vdua/partido-vip
=> feat: matches block initial commit

blocks/header/header.css, blocks/header/header.js, blocks/header/popupMenu.css, blocks/header/topMenu.css, blocks/header/utils.js, blocks/hero/hero.css, styles/lazy-styles.css, styles/styles.css
Fix #71
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/area-vip/partido-vip
- After: https://bug-71--realmadrid--hlxsites.hlx.page/area-vip/partido-vip
=> 71 - fallback fonts for header and some other adjustments

scripts/scripts.js
Fix #84
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/ar/vip-area
- After: https://84-support-for-arabic--realmadrid--hlxsites.hlx.page/ar/vip-area
=> 84 - add support for arabic

blocks/vip-areas/vip-areas.css, blocks/vip-locations/vip-locations.css, blocks/vip-sections/vip-sections.css
Fix #87 #88 #89
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/ar/vip-area/matchday-hospitality
- After: https://87-88-89-rtl-support--realmadrid--hlxsites.hlx.page/ar/vip-area/matchday-hospitality
=> 87 - 88 - 89 - rtl support in different blocks

blocks/header/header.js, blocks/header/languageSelector.js, blocks/hero/hero.css, styles/lazy-styles.css, styles/styles.css
Fix #101
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/ar/vip-area/matchday-hospitality
- After: https://101-rtl-heading-adjustments--realmadrid--hlxsites.hlx.page/ar/vip-area/matchday-hospitality
=> 101 rtl heading adjustments

blocks/area-features/area-features.css
Fix #104
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/area-vip
- After: https://issue-104--realmadrid--hlxsites.hlx.page/area-vip
=> bug: fixing width of area-features block

blocks/banner-carousel/banner-carousel.css, blocks/banner-carousel/banner-carousel.js, styles/styles.css
This PR includes the main section default content styling for tour detail pages:
Sharepoint: https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B8D20B16E-A77E-4D18-90A4-45AC96A54C39%7D&file=classic.docx&action=default&mobileredirect=true&DefaultItemOpen=1 
Fix #95
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/tour-bernabeu/classic
- After: https://95-tour-detailpage-deafultcontent--realmadrid--hlxsites.hlx.page/tour-bernabeu/classic
=> 95 tour default content implementation

sites/blocks/carousel/carousel.css, sites/blocks/carousel/carousel.js, sites/styles/styles.css
This branch new-31-add-popup-to-carousel-block was created to apply changes related to the '31-add-popup-to-carousel-block' feature. The previous branch was facing complex merge conflicts with the main branch due to structural changes. Therefore, a new branch was created from the latest main branch and the necessary changes were reapplied here to avoid those conflicts.
Fix https://github.com/hlxsites/realmadrid/issues/31
Test URLs:
Before: https://main--realmadrid--hlxsites.hlx.page/area-vip/partido-vip/silver-club-127
After: https://new-31-add-popup-to-carousel-block--realmadrid--hlxsites.hlx.page/area-vip/partido-vip/silver-club-127
=> Merge changes for ''31-add-popup-to-carousel-block" 

helix-query.yaml, helix-sitemap.yaml
Fix #120
Test URLs:
- Before: https://main--<repo>--<owner>.hlx.page/
- After: https://<branch>--<repo>--<owner>.hlx.page/
=> updating sitemap and query for tour section

sites/blocks/hero-tour/hero-tour.css, sites/blocks/related-tours/related-tours.css, sites/blocks/ticket-card-list/ticket-card-list.css, sites/blocks/ticket-card-list/ticket-card-list.js
Fix #137
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/colegios/classic-temporal
- After: https://137-ticket-block-issues--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/colegios/classic-temporal
=> 137 fixed label , tour visibility for related tours block, minor css issue

sites/blocks/area-features/area-features.js, sites/blocks/vip-sections/vip-sections.js, sites/styles/lazy-styles.css
- loading 360 degree view iframe on click rather than IntersectionObserver since that is not working for arabic
Fix #140
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.live/sites/ar/vip-area
- After: https://lhs-ar--realmadrid--hlxsites.hlx.live/sites/ar/vip-area
=> bug: improve lh score for ar language

sites/blocks/header/header.css, sites/blocks/header/languageSelector.css, sites/blocks/header/popupMenu.css
Fix #118
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/ar/vip-area
- After: https://header-rtl--realmadrid--hlxsites.hlx.page/sites/ar/vip-area
=> bug: making header work for rtl

sites/blocks/hero-tour-detail/hero-tour-detail.css, sites/blocks/hero-tour-detail/hero-tour-detail.js
Adds the Hero Block at the top of a tour detail page.
Fix #144 
Test URLs:
Normal Tour:
- Before:  https://main--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/premium
- After: https://144-tour-detail-hero-block--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/premium
Combo Tour:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/colegios/combinado-parque-warner
- After: https://144-tour-detail-hero-block--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/colegios/combinado-parque-warner
=> 144 tour detail hero block

sites/blocks/header/auth.js, sites/blocks/header/header.css, sites/blocks/header/header.js, sites/scripts/scripts.js
Fix #67
Test URLs:
- After: https://67-auth-token-refresh--realmadrid--hlxsites.hlx.page/sites/area-vip
=> feat: 67 - implement authentication, token refresh and user account logic

sites/blocks/hero-tour-detail/hero-tour-detail.js, sites/scripts/scripts.js, sites/styles/styles.css
Fix #158 
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/colegios/combinado-zoo-aquarium
- After: https://feat-158-tour-detail-fragments--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/colegios/combinado-zoo-aquarium
=> 158 - make tour detail blocks includable as fragments

sites/blocks/columns/columns.css, sites/blocks/columns/columns.js, sites/scripts/scripts.js
Modifying columns.js and columnsl.css and scripts.js. Creating new js function bindSwipeToElementWithForce in scripts.js that, in addition to bind the Swipe to an element, it calculates ‘swipeDistance’. This allows to handle swipe force without modifying your original bindSwipeToElement function, thus avoiding potential regressions.
I tried to handle the swipe force to calculate the distance and then use it to determine how many slides to scroll. I also tried to animate the scroll more smoothly by using the browser's built-in requestAnimationFrame function.
After testing mobile tabs swiping on a browser mobile emulator, I can feel that the swiping behaviour is not perfect as it can be expected when using the swiper.js library. 
I don't know if this can be due to differences in the way …
=> New smooth slider logic using JS new function instead of pure CSS

sites/blocks/matches/matches.js
To reproduce, temporarily update the `aem-gq-endpoint` and check both the URLs below.
Fix #163
Test URLs:
- After: https://empty-matches--realmadrid--hlxsites.hlx.page/sites/area-vip
=> bug: handling matches block in case api doesn't return any data

sites/blocks/teaser/teaser.css, sites/blocks/teaser/teaser.js
Fix #178 
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/area-vip/partners-internacionales
- After: https://178-teaser--realmadrid--hlxsites.hlx.page/sites/area-vip/partners-internacionales
=> 178 new teaser block for international partners page

helix-sitemap.yaml, sitemap-index.xml, sites/blocks/header/languageSelector.js, sites/scripts/scripts.js
Fix #186 
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu
- After: https://186-segregate-sitemap--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu
=> 186 segregate sitemap

sites/blocks/hero-tour/hero-tour.js, sites/scripts/delayed.js
Please always provide the [GitHub issue(s)](https://github.com/hlxsites/realmadrid/issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix https://github.com/hlxsites/realmadrid/issues/148
Test URLs:
Before: https://main--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/colegios
After: https://148-lhs-improvements--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/colegios
=> 148 lhs improvements

sites/blocks/contact-card/contact-card.css
Fix #185
Test URLs:
- After: https://185-contact-card-alignment--realmadrid--hlxsites.hlx.page/sites/area-vip
Without Fax: https://185-contact-card-alignment--realmadrid--hlxsites.hlx.page/sites/area-vip
With Fax: https://185-contact-card-alignment--realmadrid--hlxsites.hlx.page/drafts/vdua/area-vip
=> bug: fixing alignment of contact card without fax number

sites/blocks/vip-sections/vip-sections.css
Fix #184
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/area-vip/partido-vip
- After: https://184-vip-sections--realmadrid--hlxsites.hlx.page/sites/area-vip/partido-vip
=> bug: enabling more than 2 cards in the vip sections block

sites/blocks/header/auth.js, sites/blocks/header/header.css, sites/blocks/header/header.js
- Takes the first letter of the first name
- and the first letter of the first surname
Fix #211 
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.live/sites/area-vip
- After: https://211-user-initials--realmadrid--hlxsites.hlx.live/sites/area-vip
=> 211 use only first letter of first name / surname

helix-sitemap.yaml, sites/blocks/header/languageSelector.js
=> 218 - segregate sitemaps

sites/blocks/header/header.css, sites/blocks/header/header.js
Fix https://github.com/hlxsites/realmadrid/issues/225
Test URLs:
- After: https://headerColor--realmadrid--hlxsites.hlx.page/sites/area-vip
=>  fix: RM icon and login button hover color

sites/blocks/footer/footer.css, sites/blocks/footer/footer.js, sites/blocks/header/header.css, sites/styles/styles.css
Fix https://github.com/hlxsites/realmadrid/issues/231 and https://github.com/hlxsites/realmadrid/issues/229
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/area-vip#
- After: https://sociallinks--realmadrid--hlxsites.hlx.page/sites/area-vip#
=> fix: hover social and bottom links - set primary color

sites/blocks/matches/matches.css
Fix #111 
Test URLs:
- After: https://matches-rtl--realmadrid--hlxsites.hlx.page/sites/area-vip
depends on #240
=> bug: making matches block rtl ready

sites/blocks/matches/matches.js
Fix #239 
Test URLs:
- After: https://matches-2--realmadrid--hlxsites.hlx.page/sites/area-vip
=> bug: Matches block shows no matches
