blocks/contact-card/contact-card.css
To render the contact card horizontally , you have to add `homepage` as a style to the section metadata:
Fix #47
Test URLs:
- Before: homepage:  https://main--realmadrid--hlxsites.hlx.page/area-vip
Non homepage: https://main--realmadrid--hlxsites.hlx.page/area-vip/partido-vip
- After: homepage:  https://47-contact-card-homepage--realmadrid--hlxsites.hlx.page/area-vip
Non homepage: https://47-contact-card-homepage--realmadrid--hlxsites.hlx.page/area-vip/partido-vip
=> 47 Area VIP - contact card horizontal display for home page

blocks/vip-sections/vip-sections.js
Fix #76
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/
- After: https://fix-76-vip-sections-filter-anchor-url--realmadrid--hlxsites.hlx.page/
=> fix: VIP Sections break when the URL contains an anchor

blocks/area-features/area-features.css, blocks/area-features/area-features.js
- the header has the same class as the header of the modal. Renamed the classname to modal-header
Fix #77
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/area-vip
- After: https://77-header-area-features--realmadrid--hlxsites.hlx.page/area-vip
=> bug: fixing the header of the modal in area features

blocks/area-features/area-features.css
Fix #92
Open the modal dialog on clicking any features icon in info section and notice the location of the close (x) icon.
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/ar/vip-area
- After: https://issue-92--realmadrid--hlxsites.hlx.page/ar/vip-area
=> making the close button in modal dialog move to left for rtl languages

blocks/area-features/area-features.css
since margin-inline-end has better browser support
Fix #92
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.live/ar/vip-area
- After: https://issue-92--realmadrid--hlxsites.hlx.live/ar/vip-area
=> 92-1 fixing close button using margin-inline property instead of inset-inline

sites/blocks/columns/full-columns.css, sites/blocks/columns/organize-visit.css, sites/styles/styles.css
This PR:
- removes the button style for the last link in tour's default content wrapper section
- unifies the text colours of the blocks and default content to var(--text-color) aka #43526E
Fix #119 
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu
- After: https://119-tour-link-defaultcontent--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu
=> feat: [tour] default content, removed button and standardized text color

sites/scripts/scripts.js, sites/styles/styles.css
Fix #134
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/authoring-guide/areavip
- After: https://134-documentation--realmadrid--hlxsites.hlx.page/authoring-guide/areavip
=> 134 - add basic styling for documentation pages

sites/blocks/footer/footer.css, sites/blocks/footer/footer.js, sites/blocks/header/header.js, sites/blocks/matches/matches.css, sites/blocks/matches/matches.js
Fix #139
- fixed color contrast
- moved `h3`/`h4` elements that were child of `ul`. `ul` should only have `li` as its direct child.
- added `alt` attribute to images correctly. In some cases it was added to `a`
- added aria-label to form elements.
Test URLs:
- After: https://lhs--realmadrid--hlxsites.hlx.page/sites/area-vip
=> bug: improving accessibility score in LH

sites/blocks/banner-carousel/banner-carousel.css, sites/blocks/banner-carousel/banner-carousel.js, sites/blocks/columns/organize-visit.css, sites/scripts/scripts.js, sites/styles/styles.css
This PR contains the redesign of the banner-carousel block, which can be created as a two coulmns table where as a first element you need to put the image and as a second element the text.
sharepoint page:
https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B069DCEFA-C06B-49A4-8432-E8F64B6CF4A6%7D&file=tour-bernabeu.docx&action=default&mobileredirect=true
This PR contains also text harmonization to 15px and the removal of section's styling like "padding-bottom-small" or "main-section"
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/en/tour-bernabeu
- After: https://fix-banner-carousel-redesign--realmadrid--hlxsites.hlx.page/sites/en/tour-bernabeu
=> banner-carousel block redesign + section style classes removed

sites/blocks/carousel/carousel.css, sites/blocks/carousel/carousel.js, sites/styles/styles.css
This PR adds swipe support to carousel block and includes some style enhancemntes in mobile view
Fix #132 
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/en/vip-area/matchday-hospitality/silver-club-227
- After: https://132-add-slider-to-vip-area-carousel--realmadrid--hlxsites.hlx.page/sites/en/vip-area/matchday-hospitality/silver-club-227
=> feat: [vip] added swipe support to carousel

sites/blocks/table/table.css, sites/blocks/table/table.js
I've introduced the table block, contained in the block collection, to help us create some block examples in the authoring guide:
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/authoring-guide/tourbernabeu#banner-carousel
- After: https://feat-table-block--realmadrid--hlxsites.hlx.page/authoring-guide/tourbernabeu#banner-carousel
=> Added table block to help authoring guide creation

sites/blocks/hero-tour/hero-tour.css, sites/blocks/hero-tour/hero-tour.js
Changes:
- block property `Promo Title` no longer required
- Bold/italic/underline/paragraphs formating of `promo` in word gets preserved
- In desktop view, each paragraph is rendered on a separate line
- in mobile view, addtionally each bold text gets rendered on a seprate line, normal text font gets smaller.
Fix #167
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu
- After: https://167-tour-hero-promo--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu
=> 167 tour hero Support for Bold, Italic, Underline formatting and mulitline text

sites/blocks/content-header/content-header.js
- Uses first H1 title in main content as title for content header if defined
- otherwise falls back to page title 
Fix #129
Test URLs:
- Before: 
Page with a H1 title in content:
https://main--realmadrid--hlxsites.hlx.page/sites/hi/vip-area/faqs
Page with no H1 title in content:
https://main--realmadrid--hlxsites.hlx.page/sites/area-vip/faq
- After: 
Page with a H1 title in content:
https://129-faq-title--realmadrid--hlxsites.hlx.page/sites/hi/vip-area/faqs
Page with no H1 title in content:
https://129-faq-title--realmadrid--hlxsites.hlx.page/sites/area-vip/faq
=> 129 use h1 title for FAQ page if defined

sites/blocks/hero-tour/hero-tour.css, sites/blocks/hero-tour/hero-tour.js, sites/blocks/related-tours/related-tours.css, sites/scripts/scripts.js
- added swipping for the tour navigation in the hero-tour block
- added swipping for the sub category tickets (combo tickets) in the hero-tour block
- added swipping for the sub category tickets (combo tickets) in the related-tours block
- added placeholders for the sub category title/subtitle in related tours block
- other small fixes/improvements
Fix #136
Test URLs:
- Before:
Tour Navigation Swipping / Combo Tickets swipping in hero tour block:
https://main--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/colegios
Combo Tickets swipping in related tours block
https://main--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/colegios/classic
- After: 
Tour Navigation Swipping / Combo Tickets swipping in hero tour block:
https://136-tour-hero-swipe--realmadrid--hlxsites.hlx.page/sites/tour …
=> 136 swipping tour navigation and sub categories

sites/blocks/columns/organize-visit.css, sites/scripts/scripts.js
- fixed arrow icon in 'Organze your visit' footer section
- removed icon reference in `sites/tour-bernabeu/en/fragments/organize-your-visit.docx` and `sites/tour-bernabeu/fragments/organize-your-visit.docx`
- added check if tour nav exists before trying to scroll active nav into view
- 
Fix #176 
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu
- After: https://176-arrow-icon--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu
=> 176 fixed arrow icon in footer, added check if tour nav exists

sites/scripts/delayed.js
Based on customer validation: https://adobe-dx-support.slack.com/archives/C04L2G6GF8X/p1688481906054629?thread_ts=1682323232.901519&cid=C04L2G6GF8X
> The value of the levels (pageLevel1, pageLevel2...) is not correct. pageLevel1 has the same value as pageSection and this should not be the case. Example: https://main--realmadrid--hlxsites.hlx.live/sites/fr/tour-bernabeu/ecoles/guidee, the correct values would be: pageSection "tour", pageLevel1 = "colegios", pageLevel2 = "guiada", pageLevel3 = ""
> Variable values must use the character "_" instead of "-" to separate values.
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.live/sites/fr/tour-bernabeu/ecoles/guidee
- After: https://fix-data-layer-variables--realmadrid--hlxsites.hlx.live/sites/fr/tour-bernabeu/ecoles/guidee
=> fix: data layer variables

sites/scripts/delayed.js
This is the only page where we need to track under page name and page levels, an information that is not present in the page URL - the section selected on that page ('individual').
See conversation with customer: https://adobe-dx-support.slack.com/archives/C04L2G6GF8X/p1688558090628499?thread_ts=1682323232.901519&cid=C04L2G6GF8X
Alternatives:
* take the value from the `keywords` meta tag => not working, because the value would be in the language of the page and we need to track it in the primary language
* take the value from a separate `tour-category` meta tag => adds additional content authoring work and this case only applies to a single page
* take the value from a class of the hero-tour block => less preferable, as it ties the data layer tracking to the block implementation
Test …
=> fix: for tour section page the current selected section 'individual' needs to be tracked as well

404.html
- If `localhost ` or `.hlx.` domain, Franklin default 404 page is shown.
- Otherwise redirects to production domain error page , `<locale>/error/not-found`
- Tries to pick locale , defaults to `en-ES` otherwise
Fix #190
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/
- After: https://190-404-redirect--realmadrid--hlxsites.hlx.page/
NOTE: Lighthouse score will not work in this case as its a 404 page causing it to fail. Also the redirect will only trigger when on a live domain.
=> 190 404 redirect

sites/blocks/vip-areas/vip-areas.js
- Adds an optional `Category `property to the` vip-areas` block
- If not set it defaults to` vip-area-detail`
- if set to empty or invalid value nothing gets listed
Updated authoring docu to reflect the changes:
https://main--realmadrid--hlxsites.hlx.page/authoring-guide/areavip#vip-areas
Fix #203
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.live/sites/area-vip
- After: https://203-VIP-areas-cat--realmadrid--hlxsites.hlx.live/sites/area-vip
=> 203 Add category setting to vip area block

sites/blocks/hero-tour/hero-tour.css, sites/blocks/related-tours/related-tours.css, sites/styles/styles.css
- fixed indentation for tour datail page content
- fixed indentation for tour cards
Fix #192
Test URLs:
- Before:
https://main--realmadrid--hlxsites.hlx.page/sites/ar/tour-bernabeu/premium
https://main--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/premium
- After: 
https://195-arabic--realmadrid--hlxsites.hlx.page/sites/ar/tour-bernabeu/premium
https://195-arabic--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/premium
=> 192 fixed some indentation issues for arabic

sites/blocks/hero/hero.js
- initially it only adds the `source` element for the proper video size, `mobile `or `desktop`
- if media breakpoint is hit  ( `min-width:990px` ) , it adds the other `source` tag
NOTE: open developer console, go to `network `tab, filter by `media`, resize window to see when vidoes get loaded.
Fix #148
Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.live/sites/area-vip
- After: https://148-video--realmadrid--hlxsites.hlx.live/sites/area-vip
=> 148 only load mobile/desktop hero video as needed.

sites/blocks/header/popupMenu.css
- adds vertical scrolling for the pop up menu, when the width is > 1056px and the browser window height is to small.
- It adds vertical scrolling to the main menu and the sub menu
- the image that appears in a 3rd column for width > 1160px is not scrolling
Fix #212
Test URLs:
- After: https://212-popupmenu-scroll--realmadrid--hlxsites.hlx.page/sites/area-vip
To Test:
- Open Developer console
- make height small
- open pop up menu, go to 'Club' which has a large sub menu
- change width to see the different menu colums appear with the scrollbar
- scroll main / sub menu 
- resize height to make scrollbars disappear
=> 212 Vertical scroll for pop up menu when width > 1056px 

sites/blocks/content-header/content-header.js, sites/blocks/hero/hero.css, sites/blocks/hero/hero.js, sites/blocks/vip-areas/vip-areas.js, sites/scripts/scripts.js
adds navigation to the hero block in the VIP section:
- all pages below VIP root get a link back to parent page
- if page has direct children they get listed unless the page category starts with `vip-area-detail`
- it loads the query index in non-blocking way for VIP Area pages once and stores it in `window.vipIndex.data`
- the index is used by the hero block to add the navigation
- by vip-areas block to get all detail pages for the selected category
- by the faq content-header block to render the breadcrumb 
Fix #200
Test URLs:
- Before:
https://main--realmadrid--hlxsites.hlx.live/sites/area-vip
https://main--realmadrid--hlxsites.hlx.live/sites/area-vip/faq
https://main--realmadrid--hlxsites.hlx.live/sites/en/vip-area/matchday-hospitality …
=> add nav to VIP hero image

sites/scripts/delayed.js
Per customer request: https://adobe-dx-support.slack.com/archives/C04L2G6GF8X/p1689926189001269?thread_ts=1682323232.901519&cid=C04L2G6GF8X
Test URLs:
- After: https://dl-page-load-type--realmadrid--hlxsites.hlx.page/sites/area-vip
=> feat: track pageLoadType in the data layer always set to sequential
